#**Implemented By Muhammad Hanan Asghar**

#**Loading Data And Preprocessing**

I am using a simple Eassy on Nature
Source Link: https://www.toppr.com/guides/essays/nature-essay/

In [43]:
data = """
Nature is an important and integral part of mankind.\n
It is one of the greatest blessings for human life; \n
however, nowadays humans fail to recognize it as one. \n
Nature has been an inspiration for numerous poets, writers, artists \n
and more of yesteryears. This remarkable creation inspired them to write\n
poems and stories in the glory of it. They truly valued nature which reflects\n
in their works even today. Essentially, nature is everything we are surrounded\n
by like the water we drink, the air we breathe, the sun we soak in,\n
the birds we hear chirping, the moon we gaze at and more. Above all,\n
it is rich and vibrant and consists of both living and non-living things.\n
Therefore, people of the modern age should also learn something\n
from people of yesteryear and start valuing nature before it gets too late.\n
Nature has been in existence long before humans and ever since it has taken care of mankind and nourished it forever. In other words, it offers us a protective layer which guards us against all kinds of damages and harms. Survival of mankind without nature is impossible and humans need to understand that.

If nature has the ability to protect us, it is also powerful enough to destroy the entire mankind. Every form of nature, for instance, the plants, animals, rivers, mountains, moon, and more holds equal significance for us. Absence of one element is enough to cause a catastrophe in the functioning of human life.

We fulfill our healthy lifestyle by eating and drinking healthy, which nature gives us. Similarly, it provides us with water and food that enables us to do so. Rainfall and sunshine, the two most important elements to survive are derived from nature itself.

Further, the air we breathe and the wood we use for various purposes are a gift of nature only. But, with technological advancements, people are not paying attention to nature. The need to conserve and balance the natural assets is rising day by day which requires immediate attention.
In order to conserve nature, we must take drastic steps right away to prevent any further damage. The most important step is to prevent deforestation at all levels. Cutting down of trees has serious consequences in different spheres. It can cause soil erosion easily and also bring a decline in rainfall on a major level.
Polluting ocean water must be strictly prohibited by all industries straightaway as it causes a lot of water shortage. The excessive use of automobiles, AC’s and ovens emit a lot of Chlorofluorocarbons’ which depletes the ozone layer. This, in turn, causes global warming which causes thermal expansion and melting of glaciers.

Therefore, we should avoid personal use of the vehicle when we can, switch to public transport and carpooling. We must invest in solar energy giving a chance for the natural resources to replenish.

In conclusion, nature has a powerful transformative power which is responsible for the functioning of life on earth. It is essential for mankind to flourish so it is our duty to conserve it for our future generations. We must stop the selfish activities and try our best to preserve the natural resources so life can forever be nourished on earth.
"""

In [44]:
print(data)


Nature is an important and integral part of mankind.

It is one of the greatest blessings for human life; 

however, nowadays humans fail to recognize it as one. 

Nature has been an inspiration for numerous poets, writers, artists 

and more of yesteryears. This remarkable creation inspired them to write

poems and stories in the glory of it. They truly valued nature which reflects

in their works even today. Essentially, nature is everything we are surrounded

by like the water we drink, the air we breathe, the sun we soak in,

the birds we hear chirping, the moon we gaze at and more. Above all,

it is rich and vibrant and consists of both living and non-living things.

Therefore, people of the modern age should also learn something

from people of yesteryear and start valuing nature before it gets too late.

Nature has been in existence long before humans and ever since it has taken care of mankind and nourished it forever. In other words, it offers us a protective layer which guar

In [45]:
data = data.replace('\ufeff','').replace('\n','').replace('\r','')

In [46]:
data

'Nature is an important and integral part of mankind.It is one of the greatest blessings for human life; however, nowadays humans fail to recognize it as one. Nature has been an inspiration for numerous poets, writers, artists and more of yesteryears. This remarkable creation inspired them to writepoems and stories in the glory of it. They truly valued nature which reflectsin their works even today. Essentially, nature is everything we are surroundedby like the water we drink, the air we breathe, the sun we soak in,the birds we hear chirping, the moon we gaze at and more. Above all,it is rich and vibrant and consists of both living and non-living things.Therefore, people of the modern age should also learn somethingfrom people of yesteryear and start valuing nature before it gets too late.Nature has been in existence long before humans and ever since it has taken care of mankind and nourished it forever. In other words, it offers us a protective layer which guards us against all kinds 

In [47]:
# For Removing Punctuations
import string
translator = str.maketrans(string.punctuation, ' '*len(string.punctuation)) #map punctuation to space
new_data = data.translate(translator)

In [48]:
new_data

'Nature is an important and integral part of mankind It is one of the greatest blessings for human life  however  nowadays humans fail to recognize it as one  Nature has been an inspiration for numerous poets  writers  artists and more of yesteryears  This remarkable creation inspired them to writepoems and stories in the glory of it  They truly valued nature which reflectsin their works even today  Essentially  nature is everything we are surroundedby like the water we drink  the air we breathe  the sun we soak in the birds we hear chirping  the moon we gaze at and more  Above all it is rich and vibrant and consists of both living and non living things Therefore  people of the modern age should also learn somethingfrom people of yesteryear and start valuing nature before it gets too late Nature has been in existence long before humans and ever since it has taken care of mankind and nourished it forever  In other words  it offers us a protective layer which guards us against all kinds 

In [49]:
import tensorflow
from tensorflow.keras.preprocessing.text import Tokenizer
import pickle

In [50]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts([new_data])

# saving the tokenizer for predict function.
pickle.dump(tokenizer, open('tokenized_data.pkl', 'wb'))

In [51]:
tokenizer

#**What is Tokenization in NLP?**

Tokenization is essentially splitting a phrase, sentence, paragraph, or an entire text document into smaller units, such as individual words or terms. Each of these smaller units are called tokens.

#**Sequences**

basically it means to convert words or text data into integers.

In [52]:
sequence_data = tokenizer.texts_to_sequences([new_data])[0]
vocab_size = len(tokenizer.word_index) + 1

In [53]:
print("Sequences Size:",len(sequence_data))
print("Vocabulary Size:",vocab_size)

Sequences Size: 533
Vocabulary Size: 272


Means One Word is Input and Other Word is Output

In [54]:
sequences = []
for i in range(1, len(sequence_data)):
  words = sequence_data[i - 1 : i + 1]
  sequences.append(words)

In [55]:
print("Total Sequences:",len(sequences))

Total Sequences: 532


In [56]:
import numpy as np
sequences = np.array(sequences)

In [57]:
X, Y = sequences[:, 0], sequences[:, 1]

In [58]:
X = np.array(X)
Y = np.array(Y)

In [59]:
from tensorflow.keras.utils import to_categorical

In [60]:
X

array([  5,   8,  36,  22,   2,  70,  71,   3,  15,   6,   8,  23,   3,
         1,  72,  73,  10,  37,  16,  74,  75,  24,  76,   4,  77,   6,
        38,  23,   5,  14,  39,  36,  78,  10,  79,  80,  81,  82,   2,
        25,   3,  83,  40,  84,  85,  86,  87,   4,  88,   2,  89,   9,
         1,  90,   3,   6,  91,  92,  93,   5,  12,  94,  95,  96,  97,
        98,  99,   5,   8, 100,   7,  17, 101, 102,   1,  18,   7, 103,
         1,  41,   7,  42,   1, 104,   7, 105,   9,   1, 106,   7, 107,
       108,   1,  43,   7, 109,  44,   2,  25, 110,  19,   6,   8, 111,
         2, 112,   2, 113,   3, 114,  45,   2, 115,  45, 116,  46,  26,
         3,   1, 117, 118,  47,  27, 119, 120,  26,   3, 121,   2, 122,
       123,   5,  48,   6, 124, 125, 126,   5,  14,  39,   9, 127, 128,
        48,  24,   2, 129, 130,   6,  14, 131, 132,   3,  15,   2,  49,
         6,  50,   9, 133, 134,   6, 135,  13,  11, 136,  51,  12, 137,
        13, 138,  19, 139,   3, 140,   2, 141, 142,   3,  15, 14

In [61]:
Y

array([  8,  36,  22,   2,  70,  71,   3,  15,   6,   8,  23,   3,   1,
        72,  73,  10,  37,  16,  74,  75,  24,  76,   4,  77,   6,  38,
        23,   5,  14,  39,  36,  78,  10,  79,  80,  81,  82,   2,  25,
         3,  83,  40,  84,  85,  86,  87,   4,  88,   2,  89,   9,   1,
        90,   3,   6,  91,  92,  93,   5,  12,  94,  95,  96,  97,  98,
        99,   5,   8, 100,   7,  17, 101, 102,   1,  18,   7, 103,   1,
        41,   7,  42,   1, 104,   7, 105,   9,   1, 106,   7, 107, 108,
         1,  43,   7, 109,  44,   2,  25, 110,  19,   6,   8, 111,   2,
       112,   2, 113,   3, 114,  45,   2, 115,  45, 116,  46,  26,   3,
         1, 117, 118,  47,  27, 119, 120,  26,   3, 121,   2, 122, 123,
         5,  48,   6, 124, 125, 126,   5,  14,  39,   9, 127, 128,  48,
        24,   2, 129, 130,   6,  14, 131, 132,   3,  15,   2,  49,   6,
        50,   9, 133, 134,   6, 135,  13,  11, 136,  51,  12, 137,  13,
       138,  19, 139,   3, 140,   2, 141, 142,   3,  15, 143,   

In [62]:
Y = to_categorical(Y, num_classes=vocab_size)

In [63]:
Y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [64]:
Y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

#**Model**

In [65]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Embedding

In [66]:
model = Sequential()
model.add(Embedding(vocab_size, 10, input_length=1))
model.add(LSTM(1000, return_sequences=True))
model.add(LSTM(512))
model.add(Dense(256, activation="relu"))
model.add(Dense(vocab_size, activation="softmax"))

In [67]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 1, 10)             2720      
_________________________________________________________________
lstm_2 (LSTM)                (None, 1, 1000)           4044000   
_________________________________________________________________
lstm_3 (LSTM)                (None, 512)               3098624   
_________________________________________________________________
dense_2 (Dense)              (None, 256)               131328    
_________________________________________________________________
dense_3 (Dense)              (None, 272)               69904     
Total params: 7,346,576
Trainable params: 7,346,576
Non-trainable params: 0
_________________________________________________________________


Reduce learning rate when a metric has stopped improving.

#**ModelCheckpoint**
This callback is used for storing the weights of our model after training. We save only the best weights of our model by specifying save_best_only=True. We will monitor our training by using the loss metric.
#**ReduceLROnPlateau**
This callback is used for reducing the learning rate of the optimizer after a specified number of epochs. Here, we have specified the patience as 3. If the accuracy does not improve after 3 epochs, then our learning rate is reduced accordingly by a factor of 0.2. The metric used for monitoring here is loss as well.
#**Tensorboard** 
The tensorboard callback is used for plotting the visualization of the graphs, namely the graph plots for accuracy and the loss. Here, we will only be looking at the loss graph of the next word prediction.

In [68]:
from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras.callbacks import ReduceLROnPlateau
from tensorflow.keras.callbacks import TensorBoard

checkpoint = ModelCheckpoint("nextword.h5", monitor='loss', verbose=1,
    save_best_only=True, mode='auto')

reduce = ReduceLROnPlateau(monitor='loss', factor=0.2, patience=3, min_lr=0.0001, verbose = 1)

logdir='logsnextword1'
tensorboard_Visualization = TensorBoard(log_dir=logdir)

In [69]:
from tensorflow.keras.optimizers import Adam
model.compile(loss="categorical_crossentropy", optimizer=Adam(lr=0.001), metrics=['accuracy'])

In [70]:
print("Shape of Input Data:", X.shape)
print("Shape of Output Data:",Y.shape)

Shape of Input Data: (532,)
Shape of Output Data: (532, 272)


In [ ]:
history = model.fit(X, Y, epochs=500, batch_size=12, callbacks=[checkpoint, reduce, tensorboard_Visualization])


#**Predictions Time**

In [72]:
def generate_seq(model, tokenizer, enter_text, n_pred):
  in_text, result = enter_text, enter_text
  for _ in range(n_pred):
    encoded = tokenizer.texts_to_sequences([in_text])[0]
    encoded = np.array(encoded)
    yhat = model.predict_classes(encoded)
    out_word = ''
    for word, index in tokenizer.word_index.items():
      if index == yhat:
        out_word = word
        break
    in_text, result = out_word, result + ' '+ out_word
  return result

In [73]:
generate_seq(model, tokenizer, "Nature", 15)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


'Nature has been an inspiration for the natural resources so rainfall on earth it is one'